#!/bin/sh

# variables de entorno

fondo="$HOME/.fondo_pantalla/arch-orange.jpg"

# aplicar el cursor

xsetroot -cursor_name left_ptr

# configuración para el foco del raton en la ventana que se encuentra - complemento para los efectos de raton como hyprland

bspc config focus_follows_pointer true

#sxhkd y notificador

pkill sxhkd
sxhkd &

killall dunst
dunst &



bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#borde de color 

bspc config focused_border_color "#162FBF"


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# configruración de picom

picom --config ~/.config/picom/picom.conf &

# iniciar polybar y pywal para ella 

~/.config/polybar/./launch.sh --cuts &

bash $HOME/.config/polybar/cuts/scripts/pywal.sh $fondo

# configuración para altenar al abrir una pestaña nueva

bspc config automatic_scheme alternate

# moviemiento de ventanas con el cursor hyprland

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
